
# # hiredis
# find_package(hiredis REQUIRED)
# message("${HIREDIS_LIBRARY_DEBUG}")
# message("${HIREDIS_LIBRARY_RELEASE}")
# message("${HIREDIS_INCLUDE_DIR}")
# INCLUDE_DIRECTORIES(${HIREDIS_INCLUDE_DIR})
# INCLUDE_DIRECTORIES(${HIREDIS_INCLUDE_DIR}/../)
# if (CMAKE_BUILD_TYPE STREQUAL "Debug")
#   LINK_LIBRARIES(${HIREDIS_LIBRARY_DEBUG})
# else()
#   LINK_LIBRARIES(${HIREDIS_LIBRARY_RELEASE})
# endif()


SET(MODULE_PATH "${ROOT_PROJECT_SOURCE_DIR}/3rd/redis-plus-plus/install")

SET(REDIS_PLUS_PLUS_HEADER "${MODULE_PATH}/include")
SET(REDIS_PLUS_PLUS_LIB "${MODULE_PATH}/lib/redis++_static.lib")

INCLUDE_DIRECTORIES(${REDIS_PLUS_PLUS_HEADER})
LINK_LIBRARIES(${REDIS_PLUS_PLUS_LIB})