SET(MODULE_PATH "${ROOT_PROJECT_SOURCE_DIR}/3rd/cinatra")

# options
SET(BUILD_UNIT_TESTS OFF)
SET(BUILD_EXAMPLES OFF)
SET(BUILD_PRESS_TOOL OFF)
SET(BUILD_BENCHMARK OFF)
SET(ENABLE_SANITIZER OFF)
SET(COVERAGE_TEST OFF)
SET(BUILD_WITH_LIBCXX OFF)

# ADD_SUBDIRECTORY("${MODULE_PATH}")

INCLUDE_DIRECTORIES("${MODULE_PATH}/include")

# definitions
ADD_DEFINITIONS(-DASIO_STANDALONE)
REMOVE_DEFINITIONS(-DCORO_HTTP_PRINT_REQ_HEAD)